### ISSUE TITLE
Why is Record.issues an Option[Seq]?

### ISSUE THREAD

**Issue by pidge** [swoop-inc/spark-records#4]
https://github.com/swoop-inc/spark-records/blob/969e7a4/src/main/scala/com/swoop/spark/records/Record.scala#L34

It seems odd that this is an `Option[Seq[Issue]]` instead of just a `Seq[Issue]`, since AFAICT it will never meaningfully be `Some(Seq.empty)` instead of `None`. Perhaps an explanatory comment is in order?

**Comment by ssimeonov** [comment]
The reason is optimization: a `null` is cheaper to store and process than an empty array.
