### ISSUE TITLE
Provide builded jar in release page? 

### ISSUE THREAD

**Issue by jinxuan** [swoop-inc/spark-records#5]
In the release page or in [here](https://bintray.com/swoop-inc/maven/spark-records/2.0.8). Could you please provide a builded jar so that could save user some build time?

**Comment by jinxuan** [comment]
I'm facing when build the master branch.

[error] (*:update) sbt.ResolveException: unresolved dependency: com.swoop#spark-test-sugar_2.11;1.5.0: not found
[error] Total time: 7 s, completed Feb 17, 2017 11:31:23 AM
JINXUANs-MacBook-Pro:spark-records jinxuanwu$

**Comment by ssimeonov** [comment]
@jinxuan I'm not sure why it is not resolving for you but the artifact is published. See https://dl.bintray.com/swoop-inc/maven/com/swoop/spark-test-sugar_2.11/1.5.0/

**Comment by jinxuan** [comment]
In the log I saw this warn:

[warn] Credentials file /Users/tim/.bintray/.credentials does not exist

So I create one and paste the following, and this unresolved dependency solved :
```
realm = Bintray API Realm
host = api.bintray.com
user = 
password = 
```
